# -*- coding: utf-8 -*-

words = {

    # 1) INTRO À L’ANATOMIE, GENERALITES
    "Intro à l'anatomie, généralités": {
        "Ostéologie": [
            ("Tissu osseux compact",
             "Partie dense et dure de l’os, formant la couche externe et assurant la résistance mécanique."),
            ("Tissu osseux spongieux",
             "Réseau de travées à l’intérieur de l’os, assurant la légèreté et abritant la moelle osseuse."),
            ("Moelle osseuse",
             "Tissu conjonctif mou situé dans la cavité des os, comprenant la moelle rouge (hématopoïétique) et la moelle jaune (adipeuse)."),
            ("Périoste",
             "Membrane fibreuse recouvrant la surface externe des os, essentielle à la croissance, réparation et nutrition osseuse."),
            ("Os sésamoïde",
             "Petit os enchâssé dans un tendon, comme la patella, réduisant les frottements et augmentant l'efficacité mécanique."),
            ("Hyperostose (excroissance osseuse)",
             "Épaississement ou croissance anormale d’une zone osseuse, souvent liée à un processus dégénératif ou inflammatoire."),
        ],
        "Myologie": [
            ("Fascia",
             "Couche de tissu conjonctif enveloppant ou reliant les muscles, assurant soutien, protection et transmission des forces."),
            ("Tendon",
             "Structure fibreuse reliant un muscle à un os, transmettant la force musculaire nécessaire au mouvement."),
            ("Aponévrose",
             "Membrane fibreuse plate reliant un muscle à un os ou à un autre muscle, jouant un rôle dans la stabilisation et le mouvement."),
            ("Unité motrice",
             "Ensemble constitué d’un motoneurone et des fibres musculaires qu’il innerve, coordonnant la contraction musculaire."),
            ("Excitabilité musculaire",
             "Capacité d’un muscle à répondre à un stimulus nerveux ou électrique par une contraction."),
            ("Proprioception",
             "Capacité du corps à percevoir sa position et ses mouvements dans l’espace, grâce aux récepteurs sensoriels musculaires et articulaires."),
        ],

    "Cinésiologie": [
    ("Plan sagittal", "Plan vertical divisant le corps en parties gauche et droite."),
    ("Plan frontal (coronal)", "Plan vertical divisant le corps en parties antérieure et postérieure."),
    ("Plan transversal (horizontal)", "Plan horizontal divisant le corps en parties supérieure et inférieure."),
    ("Adduction", "Mouvement qui rapproche un membre de l’axe médian du corps."),
    ("Circumduction", "Mouvement circulaire décrivant un cône, combinant flexion, abduction, extension et adduction."),
    ("Chaîne cinétique fermée", "Mouvement où l’extrémité distale (main ou pied) reste fixée sur un support."),
],

"Arthrologie": [
    ("Articulation fibreuse", "Jonction entre deux os par tissu conjonctif dense, avec une mobilité quasi nulle (ex. sutures du crâne)."),
    ("Articulation cartilagineuse", "Articulation où les os sont unis par du cartilage (ex. disques intervertébraux), offrant une mobilité modérée."),
    ("Ligament", "Bande fibreuse de tissu conjonctif reliant deux os, assurant la stabilité de l’articulation."),
    ("Mouvement de glissement", "Déplacement d’une surface articulaire sur une autre sans modification angulaire."),
    ("Lubrification synoviale", "Fonction du liquide synovial, réduisant les frottements et facilitant le mouvement articulaire."),
    ("Ménisque / bourrelet articulaire", "Structure fibrocartilagineuse améliorant la congruence et la stabilité entre les surfaces articulaires."),
],

"Pathologie": [
    ("Ostéoporose", "Diminution de la densité minérale osseuse, augmentant le risque de fractures."),
    ("Arthrite", "Inflammation articulaire d’origine infectieuse, auto-immune ou métabolique, provoquant douleurs et raideurs."),
    ("Tendinite", "Inflammation d’un tendon, généralement causée par un surmenage ou des microtraumatismes répétés."),
    ("Bursite", "Inflammation d’une bourse séreuse, entraînant douleurs et gonflements autour de l’articulation."),
    ("Dysplasie", "Développement ou formation anormale d’un tissu ou d’un organe (ex. dysplasie de la hanche)."),
    ("Fibromyalgie", "Syndrome chronique caractérisé par des douleurs musculaires diffuses, fatigue et troubles du sommeil, sans lésion apparente."),
],

    },

    # 2) ÉPAULE
    "Épaule": {
        "Ostéologie": [
            ("Clavicule", "Os long en forme de S, reliant le sternum à la scapula."),
            ("Scapula", "Os plat triangulaire situé à l’arrière du thorax (omoplate)."),
            ("Acromion", "Prolongement osseux supérieur de la scapula, formant l’extrémité de l’épaule."),
            ("Processus coracoïde", "Saillie antérieure de la scapula, point d’insertion pour ligaments et tendons."),
            ("Tubercule majeur (humérus)", "Saillie latérale de l’humérus proximal, site d’insertion musculaire."),
            ("Tubercule mineur (humérus)", "Saillie antérieure de l’humérus où s’insère le muscle subscapulaire."),
            ("Sillon intertuberculaire", "Gouttière logeant le tendon du long chef du biceps brachial."),
        ],
        "Myologie": [
            ("Deltoïde", "Muscle principal de l’épaule, composé de trois faisceaux (antérieur, moyen, postérieur)."),
            ("Coiffe des rotateurs",
             "Groupe de tendons des muscles supra-épineux, infra-épineux, petit rond et subscapulaire, stabilisant l’articulation gléno-humérale."),
            ("Grand rond",
             "Muscle postérieur reliant la scapula à l’humérus, impliqué dans l’adduction et la rotation interne."),
            ("Petit rond", "Muscle de la coiffe des rotateurs, responsable de la rotation externe de l’humérus."),
            ("Coraco-brachial", "Muscle profond reliant le processus coracoïde à l’humérus, fléchisseur du bras."),
        ],
        "Cinésiologie": [
            ("Abduction de l'épaule",
             "Mouvement d’élévation latérale du bras (principalement par le deltoïde et le supra-épineux)."),
            ("Flexion de l'épaule", "Élévation du bras vers l’avant (par le deltoïde antérieur et le grand pectoral)."),
            ("Extension de l'épaule",
             "Mouvement du bras vers l’arrière (impliquant le deltoïde postérieur et le grand dorsal)."),
            ("Rotation interne", "Rotation de l’humérus vers l’intérieur (par le subscapulaire et le grand pectoral)."),
            ("Rotation externe", "Rotation de l’humérus vers l’extérieur (par l’infra-épineux et le petit rond)."),
        ],
        "Arthrologie": [
            ("Articulation scapulo-humérale",
             "Articulation synoviale sphéroïde très mobile entre la tête humérale et la cavité glénoïde."),
            ("Articulation acromio-claviculaire",
             "Articulation plane entre l’acromion de la scapula et la clavicule, contribuant à la mobilité de l’épaule."),
            ("Articulation sterno-claviculaire",
             "Articulation entre le sternum et la clavicule, essentielle pour l’amplitude de mouvement de l’épaule."),
            ("Bourse subacromiale",
             "Bourse située sous l’acromion, réduisant les frottements entre la coiffe des rotateurs et l’os."),
        ],
        "Pathologie": [
            ("Luxation antérieure de l'épaule", "Déplacement de la tête humérale en avant de la cavité glénoïde."),
            ("Tendinite de la coiffe",
             "Inflammation d’un tendon de la coiffe des rotateurs, souvent celui du supra-épineux, limitant l’élévation du bras."),
            ("Capsulite rétractile (épaule gelée)",
             "Raideur progressive et douloureuse de l’articulation gléno-humérale."),
            ("Conflit sous-acromial",
             "Frottement du tendon du supra-épineux contre l’acromion lors de l’élévation du bras."),
            ("Arthrose acromio-claviculaire",
             "Usure du cartilage de l’articulation entre l’acromion et la clavicule, causant douleur et raideur."),
        ],
    },

    # 3) BRAS ET COUDE
    "Bras et coude": {
        "Ostéologie": [
            ("Humérus", "Os long du bras, le plus long du membre supérieur."),
            ("Épicondyle latéral de l'humérus",
             "Saillie latérale distale de l’humérus, point d’insertion des muscles extenseurs de l’avant-bras."),
            ("épicondyle médial de l'humérus",
             "Saillie médiale distale de l’humérus, point d’insertion des muscles fléchisseurs de l’avant-bras."),
            ("Olécrane (ulna)", "Pointe saillante du coude, extrémité proximale de l’ulna."),
            ("Tubérosité radiale", "Zone d’insertion du tendon du biceps brachial sur le radius."),
        ],
        "Myologie": [
            ("Biceps brachial",
             "Muscle à deux chefs, responsable de la flexion du coude et de la supination de l’avant-bras."),
            ("Muscle brachial", "Muscle profond sous le biceps, principal fléchisseur du coude."),
            ("Triceps brachial", "Muscle postérieur composé de trois faisceaux, responsable de l’extension du coude."),
            ("Anconé", "Petit muscle postérieur du coude, aidant à l’extension de l’avant-bras."),
            ("Brachio-radial",
             "Muscle de l’avant-bras, contribuant à la flexion du coude, notamment en position de semi-pronation."),
        ],
        "Cinésiologie": [
            ("Flexion du coude",
             "Mouvement rapprochant l’avant-bras du bras, réalisé par le biceps brachial et le muscle brachial."),
            ("Extension du coude",
             "Mouvement éloignant l’avant-bras du bras, assuré principalement par le triceps brachial."),
            ("Supination",
             "Rotation de l’avant-bras orientant la paume de la main vers le haut, réalisée par le biceps brachial et le muscle supinateur."),
            ("Pronation",
             "Rotation de l’avant-bras orientant la paume vers le bas, réalisée par les muscles rond pronateur et carré pronateur."),
        ],
        "Arthrologie": [
            ("Articulation huméro-ulnaire",
             "Articulation de type charnière entre l’humérus et l’ulna, permettant flexion et extension."),
            ("Articulation huméro-radiale",
             "Articulation participant à la flexion, l’extension et à la rotation du radius."),
            ("Articulation radio-ulnaire proximale",
             "Articulation permettant la pronation et la supination de l’avant-bras."),
            ("Ligament collatéral radial", "Ligament stabilisant le coude sur le côté latéral."),
            ("Ligament collatéral ulnaire", "Ligament stabilisant le coude sur le côté médial."),
        ],
        "Pathologie": [
            ("Tennis elbow (épicondylite latérale)",
             "Inflammation des tendons des muscles extenseurs au niveau de l’épicondyle latéral."),
            ("Golfer’s elbow (épitrochléite)",
             "Inflammation des tendons des muscles fléchisseurs à l’épicondyle médial."),
            ("Bursite olécranienne",
             "Inflammation de la bourse séreuse située sur l’olécrane, provoquant gonflement et douleur."),
            ("Luxation du coude",
             "Déplacement des surfaces articulaires du coude, généralement à la suite d’un traumatisme."),
        ],
    },

    "Avant-bras, poignet et main": {
        "Ostéologie": [
            ("Radius (os)",
             "Os latéral de l’avant-bras, pivotant autour de l’ulna lors de la pronation et de la supination."),
            ("Ulna", "Os médial de l’avant-bras, formant la pointe du coude à son extrémité proximale (olécrane)."),
            ("Carpe",
             "Huit os courts disposés en deux rangées : scaphoïde, lunatum, triquetrum, pisiforme (rangée proximale) ; trapèze, trapézoïde, capitatum, hamatum (rangée distale)."),
            ("Métacarpiens (I à V)", "Os longs formant la paume de la main, articulés avec le carpe et les phalanges."),
            ("Phalanges",
             "Os des doigts, organisés en trois segments (sauf le pouce qui en a deux)."),
        ],
        "Myologie": [
            ("Fléchisseurs du poignet",
             "Muscles de la loge antérieure de l’avant-bras (ex. fléchisseur radial du carpe, fléchisseur ulnaire du carpe), responsables de la flexion du poignet."),
            ("Extenseurs du poignet",
             "Muscles de la loge postérieure (ex. extenseur radial du carpe, extenseur ulnaire du carpe), assurant l’extension du poignet."),
            ("Fléchisseurs des doigts",
             "Muscles superficiels et profonds permettant la flexion des phalanges (ex. fléchisseur superficiel et profond des doigts)."),
            ("Extenseurs des doigts",
             "Muscles de la loge postérieure permettant l’extension des phalanges (ex. extenseur des doigts)."),
            ("Éminence thénar",
             "Groupe musculaire à la base du pouce (court abducteur, court fléchisseur, opposant du pouce), permettant ses mouvements fins."),
            ("Éminence hypothénar",
             "Groupe musculaire à la base du cinquième doigt (abducteur, fléchisseur, opposant du petit doigt)."),
        ],
        "Cinésiologie": [
            ("Flexion du poignet",
             "Mouvement d’inclinaison de la main vers l’avant-bras, réalisé par les fléchisseurs du poignet."),
            ("Extension du poignet",
             "Mouvement d’inclinaison de la main vers l’arrière, assuré par les extenseurs du poignet."),
            ("Abduction radiale", "Inclinaison de la main vers le côté radial (côté pouce)."),
            ("Adduction ulnaire", "Inclinaison de la main vers le côté ulnaire (côté 5e doigt)."),
            ("Opposition du pouce", "Mouvement amenant la pulpe du pouce en contact avec un autre doigt."),
        ],
        "Arthrologie": [
            ("Articulation radio-carpienne",
             "Articulation entre l’extrémité distale du radius et la première rangée du carpe, permettant flexion, extension, abduction et adduction."),
            ("Articulation médio-carpienne",
             "Articulation entre les rangées proximale et distale du carpe, contribuant à la mobilité du poignet."),
            ("Articulation métacarpo-phalangienne",
             "Articulation entre la base des phalanges proximales et les têtes des métacarpiens, permettant flexion, extension, abduction et adduction des doigts."),
            ("Articulations interphalangiennes (IPP, IPD)",
             "Articulations reliant les phalanges proximale, moyenne et distale, permettant principalement la flexion et l’extension."),
        ],
        "Pathologie": [
            ("Syndrome du canal carpien",
             "Compression du nerf médian dans le canal carpien, provoquant engourdissements et fourmillements dans les trois premiers doigts."),
            ("Fracture du scaphoïde",
             "Fracture fréquente à la suite d’une chute sur la main, caractérisée par une consolidation lente en raison de la faible vascularisation de l’os."),
            ("Doigt à ressaut",
             "Blocage douloureux d’un tendon fléchisseur au passage d’une poulie digitale, entraînant un ressaut lors de la flexion-extension du doigt."),
            ("Maladie de Dupuytren",
             "Épaississement et rétraction progressive de l’aponévrose palmaire, entraînant une flexion permanente des doigts atteints."),
        ],
    },

    "Bassin": {
        "Ostéologie": [
            ("Os coxal (ilium, ischion, pubis)",
             "Constitue la moitié latérale du bassin, formé par la fusion de l’ilion, de l’ischion et du pubis."),
            ("Crête iliaque", "Bord supérieur de l’ilium, point d’insertion musculaire important."),
            ("Tubérosité ischiatique", "Partie inférieure de l’ischion, support du corps en position assise."),
            ("EIAS (épine iliaque antéro-supérieure)",
             "Saillie antérieure de l’ilion servant d’insertion au muscle sartorius et au ligament inguinal."),
        ],
        "Myologie": [
            ("Muscle ilio-psoas", "Principal fléchisseur de la hanche, composé du psoas majeur et de l’iliaque."),
            ("Piriforme", "Muscle rotateur latéral de la hanche, s’insérant entre le sacrum et le grand trochanter."),
            ("Obturateur interne",
             "Muscle rotateur latéral profond de la hanche, s’insérant sur la membrane obturatrice et le grand trochanter."),
            ("Muscles du plancher pelvien",
             "Muscles soutenant les organes pelviens et jouant un rôle clé dans la continence urinaire et fécale."),
        ],
        "Cinésiologie": [
            ("Antéversion du bassin", "Bascule du bassin vers l’avant, accentuant la courbure lombaire (lordose)."),
            ("Rétroversion du bassin", "Bascule du bassin vers l’arrière, diminuant la courbure lombaire."),
            ("Stabilisation du bassin",
             "Maintien d’une position neutre du bassin, assurant l’équilibre entre les muscles abdominaux et lombaires."),
        ],
        "Arthrologie": [
            ("Articulation sacro-iliaque",
             "Articulation entre le sacrum et l’ilion, offrant une mobilité très limitée mais jouant un rôle dans la transmission des charges."),
            ("Symphyse pubienne",
             "Articulation cartilagineuse antérieure reliant les deux pubis, renforcée par des ligaments et légèrement mobile."),
        ],
        "Pathologie": [
            ("Syndrome sacro-iliaque",
             "Douleurs mécaniques liées à un blocage ou une irritation de l’articulation sacro-iliaque."),
            ("Fracture du bassin",
             "Fracture touchant une ou plusieurs parties du bassin (ilion, ischion, pubis), généralement due à un traumatisme sévère."),
            ("Pubalgie",
             "Douleur localisée à la région pubienne, souvent associée à une sursollicitation des muscles adducteurs ou des insertions pubiennes."),
            ("Hernie inguinale",
             "Sortie d’une portion d’intestin à travers le canal inguinal, formant une saillie dans la région de l’aine."),
        ],
        "Organes": [
            ("Vessie",
             "Organe creux et musculaire servant de réservoir à l’urine, situé en avant dans le petit bassin."),
            ("Utérus",
             "Organe musculaire creux de l’appareil reproducteur féminin, destiné à accueillir et à héberger l’embryon ou le fœtus."),
        ],
    },

    "Hanche et cuisse": {
        "Ostéologie": [
            ("Fémur", "Os le plus long du corps, s’articule avec l’acétabulum du bassin et le tibia au genou."),
            ("Tête fémorale", "Extrémité sphérique du fémur, s’emboîte dans l’acétabulum."),
            ("Col du fémur",
             "Segment reliant la tête fémorale au corps du fémur, formant un angle essentiel à la mobilité."),
            ("Grand trochanter", "Saillie latérale du fémur, point d’insertion de plusieurs muscles fessiers."),
            ("Petit trochanter", "Saillie postéro-médiale du fémur, insertion du muscle ilio-psoas."),
        ],
        "Myologie": [
            ("Quadriceps (4 muscles)",
             "Principal extenseur du genou, composé du droit fémoral et des trois vastes (latéral, médial, intermédiaire)."),
            ("Ischio-jambiers",
             "Groupe musculaire postérieur de la cuisse (biceps fémoral, semi-tendineux, semi-membraneux), fléchisseur du genou."),
            ("Sartorius",
             "Muscle le plus long du corps, fléchit la hanche et le genou, participe à la rotation externe."),
            ("Tenseur du fascia lata (TFL)",
             "Muscle latéral stabilisant la hanche et le genou via la bande ilio-tibiale."),
            ("Moyen fessier", "Muscle abducteur de la hanche, stabilise le bassin lors de l’appui unipodal."),
        ],
        "Cinésiologie": [
            ("Flexion de la hanche", "Amène la cuisse vers le tronc, réalisée par l’ilio-psoas et le droit fémoral."),
            ("Extension de la hanche",
             "Ramène la cuisse en arrière, assurée par le grand fessier et les ischio-jambiers."),
            ("Abduction de la hanche", "Éloigne la cuisse de l’axe médian, action du moyen et du petit fessier."),
            ("Adduction de la hanche", "Rapproche la cuisse de l’axe médian, réalisée par les muscles adducteurs."),
        ],
        "Arthrologie": [
            ("Articulation coxo-fémorale",
             "Articulation sphéroïde (enarthrose) entre la tête fémorale et l’acétabulum, très mobile."),
            ("Labrum acétabulaire",
             "Anneau fibrocartilagineux augmentant la profondeur de l’acétabulum pour stabiliser la hanche."),
            ("Ligament ilio-fémoral", "Puissant ligament antérieur limitant l’hyperextension de la hanche."),
        ],
        "Pathologie": [
            ("Coxarthrose", "Arthrose de la hanche entraînant une usure du cartilage de l’articulation coxo-fémorale."),
            ("Luxation congénitale de la hanche", "Malformation ou instabilité articulaire présente à la naissance."),
            ("Trochantérite",
             "Inflammation de la bourse séreuse du grand trochanter, provoquant une douleur latérale à la hanche."),
        ],
    },

    "Genou et jambe": {
        "Ostéologie": [
            ("Tibia", "Os médial robuste de la jambe, principal support du poids corporel."),
            ("Fibula (péroné)", "Os latéral plus fin, participant à la stabilité latérale de la jambe."),
            ("Crête tibiale", "Arête antérieure saillante et palpable du tibia."),
            ("Tubérosité tibiale antérieure (TTA)", "Zone d’insertion du ligament patellaire sur le tibia."),
            ("Patella (rotule)",
             "Os sésamoïde logé dans le tendon du quadriceps, protège et augmente l’efficacité du muscle."),
        ],
        "Myologie": [
            ("Quadriceps (4 chefs)",
             "Comprend les vastes latéral, médial, intermédiaire et le droit fémoral, extenseur principal du genou."),
            ("Ischio-jambiers",
             "Muscles postérieurs de la cuisse fléchissant le genou et participant à l’extension de la hanche."),
            ("Triceps sural (gastrocnémien, soléaire)",
             "Forme le mollet, responsable de la flexion plantaire et le gastrocnémien fléchit aussi le genou."),
            ("Tibial antérieur", "Muscle antérieur de la jambe assurant la dorsiflexion et l’inversion du pied."),
        ],
        "Cinésiologie": [
            ("Flexion du genou", "Rapproche la jambe de la cuisse, action des ischio-jambiers."),
            ("Extension du genou", "Redresse la jambe, réalisée par le quadriceps."),
            ("Légères rotations", "Le genou fléchi peut effectuer de petites rotations médiales et latérales."),
        ],
        "Arthrologie": [
            ("Articulation fémoro-tibiale", "Articulation de type charnière, permettant flexion et extension."),
            ("Articulation fémoro-patellaire",
             "La patella glisse dans la trochlée fémorale lors des mouvements du genou."),
            ("Ligaments croisés (ant., post.)",
             "Stabilisent le genou en contrôlant les mouvements antéro-postérieurs du tibia."),
            ("Ligaments collatéraux (méd., lat.)", "Stabilisent le genou contre les mouvements en valgus et varus."),
            ("Ménisques (méd., lat.)",
             "Fibrocartilages en forme de croissant, amortissent et augmentent la congruence articulaire."),
        ],
        "Pathologie": [
            ("Entorse du genou", "Lésion ligamentaire (souvent LCA ou LCM), survenant après un traumatisme."),
            ("Rupture du ménisque", "Déchirure des ménisques, causant douleurs et parfois blocages articulaires."),
            (
            "Tendinite rotulienne", "Inflammation du tendon rotulien, fréquente chez les sportifs pratiquant le saut."),
            ("Gonarthrose", "Arthrose du genou affectant les compartiments fémoro-tibial ou fémoro-patellaire."),
        ],
    },

    "Cheville et pied": {
        "Ostéologie": [
            ("Talus",
             "Os supérieur du tarse s’articulant avec le tibia et la fibula, transmettant le poids du corps au pied."),
            ("Calcanéus", "Os formant le talon, point d’insertion du tendon d’Achille."),
            ("Os naviculaire", "Os médial du tarse, situé entre le talus et les os cunéiformes."),
            ("Os cuboïde", "Os latéral du tarse, reliant le calcanéus au 5e métatarsien."),
            ("Os cunéiformes",
             "Trois os du tarse s’articulant avec les premiers métatarsiens."),
        ],
        "Myologie": [
            ("Tibial postérieur",
             "Muscle profond assurant la flexion plantaire, l’inversion du pied et le maintien de la voûte plantaire."),
            ("Long fibulaire",
             "Muscle latéral du mollet participant à l’éversion du pied et stabilisant la voûte plantaire."),
            ("Court fibulaire", "Muscle latéral inséré sur le 5e métatarsien, impliqué dans l’éversion du pied."),
            ("Fléchisseurs plantaires des orteils", "Muscles permettant la flexion des phalanges des orteils."),
            ("Court extenseur des orteils", "Muscle dorsal du pied assurant l’extension des orteils."),
        ],
        "Cinésiologie": [
            ("Flexion plantaire",
             "Mouvement pointant le pied vers le bas, réalisé par le gastrocnémien, le soléaire et le tibial postérieur."),
            ("Dorsiflexion",
             "Mouvement soulevant le pied vers la jambe, réalisé par le tibial antérieur et les extenseurs."),
            ("Inversion",
             "Rotation du pied amenant le bord médial vers le haut, impliquant le tibial antérieur et postérieur."),
            ("Éversion", "Rotation du pied amenant le bord latéral vers le haut, réalisée par les muscles fibulaires."),
        ],
        "Arthrologie": [
            ("Articulation talo-crurale",
             "Articulation de type charnière entre le tibia, la fibula et le talus, permettant la flexion et l’extension du pied."),
            ("Articulation subtalaire",
             "Articulation entre le talus et le calcanéus, responsable des mouvements d’inversion et d’éversion."),
            ("Ligament latéral (talo-fibulaire, calcanéo-fibulaire)",
             "Ensemble ligamentaire latéral souvent lésé lors d’entorses."),
            ("Ligament médial (deltoïde)", "Puissant ligament stabilisant la cheville sur le versant médial."),
        ],
        "Pathologie": [
            ("Entorse de la cheville",
             "Lésion ligamentaire, généralement affectant le ligament talo-fibulaire antérieur."),
            ("Fasciite plantaire", "Inflammation du fascia plantaire, provoquant une douleur localisée au talon."),
            ("Hallux valgus", "Déviation latérale du gros orteil, formant une proéminence (« oignon »)."),
            ("Tendinite d’Achille",
             "Inflammation du tendon d’Achille, souvent douloureuse à la marche et lors de la flexion plantaire."),
        ],
    },
# 9) COLONNE VERTÉBRALE
"Colonne vertébrale": {
    "Ostéologie": [
        ("Vertèbres cervicales", "Sept vertèbres (C1 à C7) très mobiles, soutenant la tête et permettant sa rotation."),
        ("Vertèbres thoraciques", "Douze vertèbres (T1 à T12) attachées aux vraies côtes, moins mobiles que les cervicales."),
        ("Vertèbres lombaires", "Cinq vertèbres (L1 à L5) robustes, supportant le poids du tronc."),
        ("Sacrum", "Os formé par la fusion de cinq vertèbres sacrées, s’articulant avec les os iliaques."),
        ("Coccyx", "Petit os terminal résultant de la fusion de plusieurs vertèbres atrophiées, vestige d’une queue."),
    ],
    "Myologie": [
        ("Muscles érecteurs du rachis", "Groupe musculaire (longissimus, ilio-costal, épineux) assurant l’extension et la posture du dos."),
        ("Muscles transversaires épineux", "Muscles profonds (multifides, rotateurs) stabilisant et permettant la rotation vertébrale."),
        ("Carré des lombes", "Muscle postérieur permettant l’inclinaison latérale du tronc et la stabilisation lombaire."),
        ("Abdominaux profonds (transverse)", "Muscle profond de la paroi abdominale, essentiel à la stabilisation du tronc."),
    ],
    "Cinésiologie": [
        ("Flexion du tronc", "Inclinaison du tronc vers l’avant, réalisée par les muscles abdominaux."),
        ("Extension du tronc", "Redressement du tronc par les muscles dorsaux."),
        ("Inclinaison latérale", "Inclinaison latérale du tronc réalisée par le carré des lombes et les obliques."),
        ("Rotation du tronc", "Rotation axiale du tronc impliquant les obliques et les muscles transversaires épineux."),
    ],
    "Arthrologie": [
        ("Disques intervertébraux", "Structures fibrocartilagineuses entre les corps vertébraux, servant d’amortisseurs."),
        ("Articulations zygapophysaires", "Articulations synoviales entre les processus articulaires supérieurs et inférieurs des vertèbres."),
        ("Ligament longitudinal antérieur", "Ligament situé à l’avant des corps vertébraux, limitant l’hyperextension."),
        ("Ligament jaune", "Ligament élastique reliant les lames vertébrales, participant au maintien de la posture."),
    ],
    "Pathologie": [
        ("Hernie discale", "Saillie du noyau pulpeux d’un disque intervertébral, pouvant comprimer un nerf spinal."),
        ("Lombalgie", "Douleur localisée dans la région lombaire, très fréquente."),
        ("Scoliose", "Courbure latérale anormale de la colonne vertébrale avec rotation des vertèbres."),
        ("Hyperlordose lombaire", "Accentuation excessive de la courbure lombaire."),
        ("Sténose spinale", "Réduction du canal rachidien, entraînant la compression de la moelle épinière ou des racines nerveuses."),
    ],
},

# 10) TÊTE, COU ET TRONC
"Tête, cou et tronc": {
    "Ostéologie": [
        ("Os frontal", "Os formant le front et la partie supérieure des orbites."),
        ("Os pariétal", "Os formant la partie supérieure et latérale du crâne."),
        ("Os temporal", "Os latéral du crâne abritant le conduit auditif et le processus mastoïde."),
        ("Maxillaire inférieur", "Seul os mobile du visage, supportant les dents inférieures."),
        ("Sternum", "Os plat antérieur du thorax, composé du manubrium, du corps et du processus xiphoïde."),
   ],
    "Myologie": [
        ("Sterno-cléido-mastoïdien", "Muscle latéral du cou permettant la flexion, la rotation de la tête et l’élévation du sternum."),
        ("Muscles scalènes", "Muscles latéraux du cou (antérieur, moyen, postérieur) contribuant à l’inclinaison latérale et à la respiration."),
        ("Trapèze (partie supérieure)", "Muscle postérieur du cou et du dos, responsable de l’élévation de la scapula et de l’extension cervicale."),
        ("Grand droit de l’abdomen", "Muscle longitudinal de la paroi abdominale, principal fléchisseur du tronc."),
        ("Obliques (interne/externe)", "Muscles abdominaux assurant la flexion, la rotation du tronc et la contention abdominale."),
    ],
    "Cinésiologie": [
        ("Flexion du cou", "Inclinaison antérieure de la tête réalisée par le sterno-cléido-mastoïdien et les scalènes."),
        ("Extension du cou", "Inclinaison postérieure de la tête assurée par le trapèze supérieur et les muscles postérieurs du cou."),
        ("Inclinaison latérale du cou", "Mouvement unilatéral de la tête vers une épaule, réalisé par le sterno-cléido-mastoïdien et les scalènes."),
        ("Rotation de la tête", "Mouvement de rotation assuré par le sterno-cléido-mastoïdien controlatéral et le splénius homolatéral."),
    ],
    "Arthrologie": [
        ("Articulation temporo-mandibulaire", "Articulation synoviale entre la mandibule et l’os temporal, essentielle à la mastication."),
        ("Articulation atlanto-occipitale", "Articulation entre la première vertèbre cervicale (atlas) et l’os occipital, permettant les mouvements de flexion/extension (mouvement « oui »)."),
        ("Articulation atlanto-axoïdienne", "Articulation pivot entre la première (atlas) et la deuxième vertèbre cervicale (axis), permettant la rotation de la tête (mouvement « non »)."),
    ],
    "Pathologie": [
        ("Torticolis", "Contracture douloureuse des muscles du cou, limitant la rotation de la tête."),
        ("Cervicalgie", "Douleur localisée dans la région cervicale, d’origines variées."),
        ("Bruxisme", "Grincement ou serrement involontaire des dents sollicitant l’articulation temporo-mandibulaire."),
        ("Hernie hiatale", "Passage d’une partie de l’estomac à travers le hiatus œsophagien du diaphragme."),
    ],
},
# 11) THORAX (avec Organes)
"Thorax": {
    "Ostéologie": [
        ("Cage thoracique", "Structure formée par le sternum, les côtes et les vertèbres thoraciques."),
        ("Sternum", "Os plat composé du manubrium, du corps et de l’appendice xiphoïde."),
        ("Vraies côtes",
         "Sept premières côtes (1 à 7), reliées directement au sternum par leur propre cartilage costal."),
        ("Fausses côtes", "Côtes 8 à 10, reliées indirectement au sternum via un cartilage commun."),
        ("Côtes flottantes", "Côtes 11 et 12, non reliées au sternum, libres en avant."),
    ],
    "Myologie": [
        ("Grand pectoral", "Muscle thoracique antérieur, responsable de l’adduction et de la rotation interne du bras."),
        ("Petit pectoral", "Muscle sous le grand pectoral, tirant la scapula en avant et en bas."),
        ("Intercostaux externes", "Muscles soulevant les côtes lors de l’inspiration."),
        ("Intercostaux internes", "Muscles abaissant les côtes lors de l’expiration forcée."),
        ("Diaphragme", "Muscle principal de la respiration, séparant le thorax de l’abdomen."),
    ],
    "Cinésiologie": [
        ("Inspiration", "Augmentation du volume thoracique par la contraction du diaphragme et des intercostaux externes."),
        ("Expiration", "Diminution du volume thoracique, processus passif ou actif via les intercostaux internes."),
        ("Mobilité costale", "Mouvements d’élévation et d’abaissement des arcs costaux."),
    ],
    "Arthrologie": [
        ("Articulations costo-vertébrales", "Articulations entre les côtes et les vertèbres thoraciques."),
        ("Articulations sterno-costales", "Articulations entre le sternum et les cartilages costaux."),
    ],
    "Pathologie": [
        ("Pneumothorax", "Présence d’air dans la cavité pleurale, provoquant le collapse d’un poumon."),
        ("Pleurésie", "Inflammation de la plèvre, douloureuse lors de la respiration."),
        ("Fractures costales", "Fractures douloureuses des côtes, pouvant entraîner des lésions pulmonaires."),
    ],
    "Organes": [
        ("Cœur", "Organe musculaire creux situé dans le médiastin, jouant le rôle de pompe circulatoire."),
        ("Poumons", "Organes spongieux responsables des échanges gazeux d’oxygène et de dioxyde de carbone."),
        ("Œsophage", "Conduit musculaire reliant le pharynx à l’estomac, traversant le thorax."),
        ("Thymus", "Glande lymphoïde située dans le médiastin, essentielle pour l’immunité chez l’enfant."),
    ],
},

# 12) ABDOMEN (avec Organes)
"Abdomen": {
    "Ostéologie": [
        ("Arcs costaux inférieurs", "Partie inférieure de la cage thoracique, marquant la limite supérieure de l’abdomen."),
        ("Vertèbres lombaires", "Cinq vertèbres (L1 à L5) formant la paroi postérieure de l’abdomen."),
    ],
    "Myologie": [
        ("Grand droit de l’abdomen", "Muscle vertical pair de la paroi abdominale, fléchisseur du tronc."),
        ("Oblique externe", "Muscle de la paroi abdominale avec des fibres obliques dirigées vers le bas et l’intérieur, impliqué dans la rotation controlatérale."),
        ("Oblique interne", "Muscle sous l’oblique externe, avec des fibres obliques vers le haut et l’intérieur, impliqué dans la rotation homolatérale."),
        ("Transverse de l’abdomen", "Muscle profond de la paroi abdominale, assurant la contention et le gainage."),
        ("Pyramidal", "Petit muscle triangulaire situé sous l’ombilic, parfois absent."),
    ],
    "Cinésiologie": [
        ("Flexion du tronc", "Inclinaison du tronc vers l’avant grâce au grand droit et aux obliques."),
        ("Rotation du tronc", "Rotation assurée par l’oblique externe d’un côté et l’oblique interne controlatéral."),
        ("Gainage abdominal", "Stabilisation du rachis par la contraction des muscles abdominaux profonds."),
    ],
    "Arthrologie": [
        ("Articulations costo-chondrales inférieures", "Jonctions entre les côtes inférieures et leurs cartilages costaux."),
        ("Symphyse lombo-sacrée", "Articulation entre la cinquième vertèbre lombaire (L5) et le sacrum."),
    ],
    "Pathologie": [
        ("Hernie ombilicale", "Sortie d’organes ou de graisse au niveau de l’ombilic par faiblesse de la paroi abdominale."),
        ("Diastasis des grands droits", "Élargissement pathologique de l’espace entre les muscles grands droits sur la ligne médiane."),
        ("Éventration", "Faiblesse de la paroi abdominale post-chirurgicale, provoquant une protrusion."),
        ("Appendicite", "Inflammation aiguë de l’appendice, pouvant nécessiter une intervention chirurgicale."),
        ("Péritonite", "Inflammation du péritoine, urgence chirurgicale en cas de perforation digestive."),
    ],
    "Organes": [
        ("Foie", "Glande volumineuse sous le diaphragme, impliquée dans le métabolisme et la production de bile."),
        ("Estomac", "Organe creux du tube digestif, responsable du stockage et de la digestion initiale des aliments."),
        ("Intestin grêle", "Constitué du duodénum, jéjunum et iléon, principal site d’absorption des nutriments."),
        ("Gros intestin", "Comprenant le côlon et le rectum, impliqué dans la réabsorption de l’eau et la formation des selles."),
        ("Pancréas", "Glande mixte sécrétant des enzymes digestives (fonction exocrine) et de l’insuline (fonction endocrine)."),
        ("Rate", "Organe lymphoïde filtrant le sang, situé sous le diaphragme à gauche."),
        ("Reins", "Organes pairs filtrant le sang pour produire l’urine."),
        ("Surrénales", "Glandes endocrines situées au sommet de chaque rein, produisant des hormones telles que l’adrénaline et le cortisol."),
    ],
},

    # ---------------------------------------------------------------------
    # PARTIES : "Anatomie", "Physiologie" ET "Pathologies"
    # ---------------------------------------------------------------------
    "Anatomie": {
        "Os": [
            ("Fémur", "Os long et massif de la cuisse, le plus long du corps humain."),
            ("Tibia", "Os long situé à l'avant de la jambe, support principal du poids."),
            ("Radius (os)", "Os long latéral de l'avant-bras, participant à la pronation et la supination."),
            ("Crâne", "Ensemble des os formant la boîte crânienne, protégeant l’encéphale."),
            ("Côtes", "Os plats et incurvés formant la cage thoracique, protégeant le cœur et les poumons."),
            ("Vertèbres",
             "Pièces osseuses formant la colonne vertébrale, divisées en régions cervicale, thoracique, lombaire, sacrée et coccygienne."),
            ("Bassin", "Ensemble osseux composé des os iliaques, du sacrum et du coccyx."),
            ("Sternum",
             "Os plat allongé situé au centre de la cage thoracique, composé du manubrium, du corps et de l’appendice xiphoïde."),
            ("Scapula (omoplate)", "Os plat et triangulaire de l’épaule, reliant le bras au tronc."),
            ("Carpe", "Ensemble de huit petits os courts formant la base du poignet."),
        ],
        "Muscles": [
            ("Deltoïde", "Muscle épais en forme de delta recouvrant l'épaule, principal abducteur du bras."),
            ("Quadriceps", "Groupe de quatre muscles à l'avant de la cuisse, principal extenseur du genou."),
            ("Biceps brachial",
             "Muscle à l'avant du bras composé de deux faisceaux, fléchisseur du coude et supinateur."),
            ("Triceps brachial", "Muscle à l'arrière du bras composé de trois faisceaux, extenseur du coude."),
            ("Grand pectoral",
             "Muscle large et épais de la poitrine, impliqué dans l’adduction et la rotation interne du bras."),
            ("Grand dorsal",
             "Muscle large du dos s'étendant du bassin aux bras, impliqué dans l’adduction, l’extension et la rotation interne du bras."),
            ("Abdominaux",
             "Groupe de muscles situés à l'avant de l'abdomen, impliqués dans la flexion du tronc et la stabilisation du tronc."),
            ("Ischio-jambiers",
             "Groupe musculaire à l'arrière de la cuisse, impliqué dans la flexion du genou et l'extension de la hanche."),
            ("Mollets",
             "Groupe musculaire composé du gastrocnémien et du soléaire, impliqué dans la flexion plantaire du pied."),
            ("Masséter", "Muscle puissant de la mâchoire, principal muscle de la mastication."),
            ("Trapèze",
             "Muscle large et triangulaire du dos et du cou, impliqué dans les mouvements de la tête, du cou et de la scapula."),
            ("Rhomboïde",
             "Muscle situé entre la colonne vertébrale et la scapula, responsable de la rétraction de la scapula."),
            ("Serratus antérieur", "Muscle dentelé situé sur les côtés de la cage thoracique, stabilise la scapula."),
            ("Intercostaux", "Muscles situés entre les côtes, essentiels à la respiration."),
            ("Sterno-cléido-mastoïdien",
             "Muscle du cou impliqué dans la flexion, la rotation de la tête et l’élévation du sternum."),
        ],
        "Organes": [
            ("Cœur",
             "Organe musculaire thoracique, assurant la circulation sanguine en pompant le sang dans tout le corps."),
            ("Poumons", "Organes pairs et spongieux, siège des échanges gazeux entre l’air et le sang."),
            ("Foie",
             "Glande volumineuse sous le diaphragme, jouant un rôle central dans le métabolisme et la production de la bile."),
            ("Estomac", "Organe creux où s'effectue le stockage et la digestion initiale des aliments."),
            ("Intestins",
             "Conduits digestifs comprenant l’intestin grêle (absorption des nutriments) et le gros intestin (formation des selles)."),
            ("Reins",
             "Organes pairs filtrant le sang pour produire l'urine et réguler diverses fonctions métaboliques."),
            ("Vessie", "Réservoir musculaire situé dans le bassin, stockant l’urine avant son évacuation."),
            ("Cerveau",
             "Organe principal du système nerveux central, responsable des fonctions cognitives et motrices."),
            ("Pancréas",
             "Glande à fonction exocrine (sécrétion d’enzymes digestives) et endocrine (sécrétion d’insuline)."),
            ("Utérus",
             "Organe creux musculaire de l’appareil reproducteur féminin, destiné à accueillir et nourrir l’embryon/fœtus."),
            ("Testicules", "Organes pairs produisant les spermatozoïdes et la testostérone."),
            ("Vagin", "Conduit musculo-membraneux de l’appareil reproducteur féminin reliant l’utérus à la vulve."),
            ("Ovaires", "Organes pairs produisant les ovules et sécrétant des hormones sexuelles féminines."),
            ("Prostate", "Glande masculine entourant l’urètre, contribuant à la composition du sperme."),
            ("Pénis", "Organe masculin permettant l’excrétion urinaire et la reproduction."),
            ("Glandes mammaires", "Glandes situées dans les seins, responsables de la production de lait maternel."),
            ("Tube digestif",
             "Ensemble des organes creux allant de la bouche à l’anus, impliqué dans la digestion et l’absorption des nutriments."),
            ("Ganglion lymphatique",
             "Structure du système lymphatique filtrant la lymphe et jouant un rôle immunitaire."),
            ("Rate", "Organe lymphoïde participant à la filtration du sang et à la réponse immunitaire."),
            ("Thymus",
             "Glande située dans le médiastin, jouant un rôle essentiel dans le développement du système immunitaire durant l’enfance."),
            ("Vésicule biliaire", "Petit organe sous le foie, stockant et concentrant la bile produite par celui-ci."),
        ],
    },
"Physiologie": {
    "Système nerveux": [
        ("Neurone", "Cellule nerveuse spécialisée dans la transmission des influx nerveux."),
        ("Synapse", "Jonction fonctionnelle permettant la transmission de signaux entre deux neurones ou un neurone et une cellule effectrice."),
        ("Moelle épinière", "Partie du système nerveux central située dans le canal vertébral, transmet les signaux entre le cerveau et le corps."),
        ("Cervelet", "Partie postérieure du cerveau, sous le cortex, responsable de l’équilibre, de la coordination motrice et du tonus musculaire."),
        ("Hypothalamus", "Région du cerveau située sous le thalamus, régulant la température corporelle, la faim, la soif et les émotions."),
        ("Réflexe", "Réponse automatique, rapide et involontaire à un stimulus."),
        ("Neurotransmetteur", "Substance chimique permettant la transmission du signal à la synapse."),
        ("Myéline", "Gaine isolante entourant les axones des neurones, augmentant la vitesse de conduction des influx nerveux."),
        ("Neuropathie", "Maladie ou lésion affectant les nerfs périphériques, entraînant des troubles sensoriels ou moteurs."),
        ("Encéphalite", "Inflammation du tissu cérébral, souvent d’origine virale."),
        ("Système limbique", "Ensemble de structures cérébrales impliquées dans la gestion des émotions et de la mémoire."),
        ("Hypophyse", "Glande endocrine à la base du cerveau, régulant la sécrétion hormonale de nombreuses glandes périphériques."),
        ("Méninges", "Enveloppes protectrices du cerveau et de la moelle épinière, composées de la dure-mère, de l’arachnoïde et de la pie-mère."),
        ("Jonction neuromusculaire", "Zone de contact où un neurone moteur stimule une fibre musculaire pour induire la contraction."),
        ("Système sympathique", "Division du système nerveux autonome responsable des réactions de stress (réponse 'combat ou fuite')."),
        ("Système parasympathique", "Division du système nerveux autonome impliquée dans les fonctions de repos, récupération et digestion."),
        ("Potentiel d'action", "Variation rapide et transitoire du potentiel électrique à la surface d’un neurone ou d’une fibre musculaire."),
        ("Plasticité cérébrale", "Capacité du cerveau à se réorganiser et à former de nouvelles connexions neuronales après une expérience ou une lésion."),
        ("Neurogenèse", "Processus de formation de nouveaux neurones, notamment dans l’hippocampe."),
        ("Circulation cérébrale", "Flux sanguin assurant l’apport d’oxygène et de nutriments au cerveau."),
    ],
    "Système digestif": [
        ("Mastication", "Broyage mécanique des aliments par les dents pour faciliter la digestion."),
        ("Déglutition", "Processus permettant le passage des aliments de la bouche à l’œsophage."),
        ("Péristaltisme", "Série de contractions musculaires propulsant le contenu du tube digestif."),
        ("Absorption", "Passage des nutriments digérés à travers la paroi intestinale vers la circulation sanguine ou lymphatique."),
        ("Digestion", "Transformation mécanique et chimique des aliments en nutriments assimilables."),
        ("Sécrétion gastrique", "Production de sucs gastriques contenant de l’acide chlorhydrique et des enzymes digestives."),
        ("Péritoine", "Membrane séreuse entourant les organes abdominaux et tapissant la cavité abdominale."),
        ("Sphincter", "Anneau musculaire régulant l’ouverture ou la fermeture d’un conduit organique."),
        ("Bile", "Liquide produit par le foie et stocké dans la vésicule biliaire, facilitant la digestion des graisses."),
        ("Enzymes digestives", "Protéines favorisant la dégradation des nutriments (amylase, lipase, protéases)."),
    ],
    "Système reproducteur": [
        ("Ovaire", "Organe féminin produisant les ovules et les hormones sexuelles."),
        ("Utérus", "Organe musculaire creux dans lequel se développe l’embryon puis le fœtus."),
        ("Trompe de Fallope", "Conduit reliant l’ovaire à l’utérus, site habituel de la fécondation."),
        ("Vagin", "Canal musculo-membraneux reliant l’utérus à la vulve, participant à la reproduction et à la naissance."),
        ("Testicule", "Glande sexuelle masculine produisant les spermatozoïdes et la testostérone."),
        ("Épididyme", "Conduit en forme de tube situé sur le testicule, où les spermatozoïdes achèvent leur maturation."),
        ("Prostate", "Glande masculine entourant l’urètre, sécrétant un liquide contribuant à la composition du sperme."),
        ("Ovulation", "Libération d’un ovule par l’ovaire au cours du cycle menstruel."),
        ("Fécondation", "Union du spermatozoïde et de l’ovule, formant un zygote."),
        ("Ménopause", "Arrêt définitif des menstruations, marquant la fin de la période reproductive féminine."),
    ],
    "Système respiratoire": [
        ("Poumon", "Organe pair et spongieux assurant les échanges gazeux entre l’air inspiré et le sang."),
        ("Trachée", "Conduit cartilagineux reliant le larynx aux bronches principales."),
        ("Bronche", "Conduit aérien issu de la trachée, conduisant l’air vers chaque poumon."),
        ("Alvéole pulmonaire", "Petite cavité terminale des bronchioles, siège des échanges gazeux entre l’air et le sang."),
        ("Diaphragme", "Muscle principal de la respiration, séparant le thorax de l’abdomen."),
        ("Hémoglobine", "Protéine présente dans les globules rouges, assurant le transport de l’oxygène et du dioxyde de carbone."),
        ("Expiration", "Phase de la respiration au cours de laquelle l’air est expulsé des poumons."),
        ("Inspiration", "Phase de la respiration au cours de laquelle l’air pénètre dans les poumons."),
        ("Asphyxie", "Manque ou absence d’oxygène dans l’organisme, pouvant entraîner la mort si non corrigé."),
        ("Apnée", "Interruption temporaire de la respiration."),
    ],
    "Système endocrinien": [
        ("Hypophyse", "Glande endocrine située sous l’hypothalamus, contrôlant la production d’hormones de plusieurs autres glandes."),
        ("Thyroïde", "Glande endocrine du cou, régulant le métabolisme via les hormones T3 et T4."),
        ("Parathyroïde", "Petites glandes situées derrière la thyroïde, régulant le taux de calcium sanguin."),
        ("Pancréas", "Glande mixte, produisant l’insuline et le glucagon (endocrine) ainsi que des enzymes digestives (exocrine)."),
        ("Surrénale", "Glande située au sommet de chaque rein, sécrétant des hormones comme le cortisol et l’adrénaline."),
        ("Hormone", "Substance chimique produite par une glande endocrine et transportée par le sang pour réguler diverses fonctions corporelles."),
        ("Diabète", "Trouble caractérisé par une hyperglycémie chronique due à un déficit ou une résistance à l’insuline."),
        ("Hypothyroïdie", "Diminution de la production d’hormones thyroïdiennes, ralentissant le métabolisme."),
        ("Hypercalcémie", "Augmentation anormale du taux de calcium dans le sang."),
        ("Insuffisance surrénalienne", "Déficit en hormones surrénaliennes, notamment le cortisol et l’aldostérone."),
    ],
    "Système cardiovasculaire": [
        ("Cœur", "Organe musculaire assurant la circulation sanguine en propulsant le sang dans le corps."),
        ("Artère", "Vaisseau transportant le sang du cœur vers les organes et tissus."),
        ("Veine", "Vaisseau ramenant le sang des organes vers le cœur."),
        ("Valve cardiaque", "Structure empêchant le reflux sanguin à l’intérieur du cœur, assurant la circulation unidirectionnelle."),
        ("Pression artérielle", "Force exercée par le sang sur les parois artérielles, essentielle à la perfusion des organes."),
        ("Athérosclérose", "Accumulation de plaques lipidiques dans la paroi des artères, réduisant leur élasticité et diamètre."),
        ("Angine de poitrine", "Douleur thoracique due à une diminution temporaire de l’apport sanguin au muscle cardiaque."),
        ("Infarctus", "Destruction partielle du muscle cardiaque en raison de l’obstruction d’une artère coronaire."),
        ("Sténose", "Réduction anormale du diamètre d’un vaisseau sanguin ou d’un canal organique."),
        ("Thrombose", "Formation d’un caillot sanguin obstruant un vaisseau sanguin, pouvant entraîner une embolie."),
    ],
},
"Pathologies": {
    "Système nerveux": [
        ("Alzheimer", "Maladie neurodégénérative entraînant une perte progressive de la mémoire et des fonctions cognitives."),
        ("Parkinson", "Affection neurologique due à la dégénérescence des neurones dopaminergiques, provoquant tremblements et rigidité."),
        ("Sclérose en plaques", "Maladie auto-immune affectant la myéline du système nerveux central."),
        ("Épilepsie", "Trouble caractérisé par des crises convulsives causées par une activité électrique anormale du cerveau."),
        ("Migraine", "Céphalée intense et pulsatile, souvent accompagnée de nausées et parfois d’aura."),
        ("Accident vasculaire cérébral", "Interruption brutale de l’apport sanguin au cerveau, d’origine ischémique ou hémorragique."),
        ("Névralgie", "Douleur intense suivant le trajet d’un nerf."),
        ("Neuropathie périphérique", "Atteinte des nerfs périphériques, engendrant des troubles sensitifs, moteurs ou autonomes."),
        ("Sciatique", "Douleur irradiant le long du nerf sciatique, généralement causée par une hernie discale."),
        ("Narcolepsie", "Trouble du sommeil caractérisé par une somnolence diurne excessive et des accès soudains de sommeil."),
    ],
    "Système digestif": [
        ("Gastrite", "Inflammation de la muqueuse de l’estomac, aiguë ou chronique."),
        ("Ulcère gastrique", "Lésion de la muqueuse gastrique ou duodénale, souvent associée à Helicobacter pylori."),
        ("Maladie de Crohn", "Inflammation chronique segmentaire du tube digestif, pouvant affecter toutes ses couches."),
        ("Rectocolite hémorragique", "Inflammation chronique affectant le côlon et le rectum."),
        ("Cancer colorectal", "Tumeur maligne du côlon ou du rectum, issue souvent d’un polype."),
        ("Appendicite", "Inflammation aiguë de l’appendice vermiforme, urgence chirurgicale fréquente."),
        ("Pancréatite", "Inflammation du pancréas, aiguë ou chronique, d’origine variée (alcool, calculs biliaires...)."),
        ("Reflux gastro-œsophagien", "Remontée acide du contenu gastrique dans l’œsophage, provoquant des brûlures (pyrosis)."),
        ("Cirrhose", "Fibrose hépatique avancée entraînant une altération irréversible de la structure hépatique."),
        ("Maladie cœliaque", "Intolérance au gluten entraînant une inflammation chronique de l’intestin grêle."),
    ],
    "Système endocrinien": [
        ("Diabète de type 1", "Maladie auto-immune entraînant la destruction des cellules bêta du pancréas, avec déficit en insuline."),
        ("Diabète de type 2", "Résistance à l’insuline, souvent associée au surpoids et à la sédentarité."),
        ("Hypothyroïdie", "Production insuffisante d’hormones thyroïdiennes, ralentissant le métabolisme."),
        ("Hyperthyroïdie", "Production excessive d’hormones thyroïdiennes, accélérant le métabolisme."),
        ("Maladie d’Addison", "Insuffisance surrénalienne chronique, entraînant fatigue, perte de poids et hypotension."),
        ("Tumeur hypophysaire", "Masse bénigne ou maligne affectant l’hypophyse et perturbant la sécrétion hormonale."),
        ("Hyperparathyroïdie", "Excès de production de l’hormone parathyroïdienne, provoquant une hypercalcémie."),
        ("Syndrome de Cushing", "Conséquence d’un excès de cortisol, avec obésité centrale et faciès lunaire."),
        ("Puberté précoce", "Développement des caractères sexuels secondaires avant l’âge normal."),
        ("Insuffisance ovarienne prématurée", "Arrêt de la fonction ovarienne avant 40 ans, provoquant une aménorrhée."),
    ],
    "Système cardiovasculaire": [
        ("Athérosclérose", "Accumulation de plaques d’athérome dans la paroi des artères, rétrécissant leur lumière."),
        ("Infarctus du myocarde", "Destruction partielle du muscle cardiaque à la suite d’une obstruction coronaire."),
        ("Insuffisance cardiaque", "Déficience de la capacité du cœur à assurer un débit sanguin suffisant."),
        ("Hypertension artérielle", "Élévation persistante de la pression artérielle au-dessus des valeurs normales."),
        ("Accident vasculaire cérébral", "Obstruction ou rupture d’un vaisseau cérébral, entraînant un déficit neurologique."),
        ("Arythmie cardiaque", "Trouble du rythme cardiaque (tachycardie, bradycardie ou irrégularité)."),
        ("Thrombose veineuse", "Formation d’un caillot sanguin dans une veine, avec risque d’embolie pulmonaire."),
        ("Phlébite", "Inflammation d’une veine, généralement associée à la formation d’un thrombus."),
        ("Artérite", "Inflammation d’une artère, avec divers mécanismes sous-jacents."),
        ("Dissection aortique", "Fissuration de la paroi interne de l’aorte, nécessitant une prise en charge urgente."),
        ("Valvulopathie", "Dysfonctionnement d’une ou plusieurs valves cardiaques, entraînant une sténose ou une régurgitation."),
        ("Angine de poitrine", "Douleur thoracique liée à une ischémie myocardique transitoire."),
        ("Anévrisme", "Dilatation localisée d’une artère due à un affaiblissement de sa paroi."),
        ("Cardiopathie congénitale", "Malformation cardiaque présente dès la naissance."),
        ("Œdème", "Accumulation de liquide dans les tissus, souvent aux membres inférieurs."),
        ("Varices", "Dilations anormales des veines superficielles, associées à une insuffisance veineuse."),
    ],
    "Système respiratoire": [
        ("Asthme", "Maladie inflammatoire chronique des voies respiratoires, caractérisée par des épisodes de dyspnée et de sifflements."),
        ("Bronchite chronique", "Inflammation persistante des bronches, souvent liée au tabagisme."),
        ("Pneumonie", "Infection aiguë du tissu pulmonaire, se manifestant par fièvre, toux et douleurs thoraciques."),
        ("Emphysème", "Destruction des alvéoles pulmonaires, entraînant une réduction de la surface d’échange gazeux."),
        ("Mucoviscidose", "Maladie génétique provoquant un épaississement des sécrétions bronchiques et pancréatiques."),
        ("Cancer bronchique", "Tumeur maligne affectant les tissus des bronches, fréquemment associée au tabac."),
        ("Mésothéliome", "Cancer de la plèvre, souvent en lien avec une exposition à l’amiante."),
        ("Apnée du sommeil", "Arrêt temporaire de la respiration pendant le sommeil, induisant une fatigue diurne."),
        ("Fibrose pulmonaire", "Épaississement du tissu pulmonaire, réduisant la capacité respiratoire."),
        ("Silicose", "Affection pulmonaire causée par l’inhalation prolongée de poussières de silice."),
    ],
    "Système reproducteur": [
        ("Endométriose", "Affection caractérisée par la présence de tissu endométrial en dehors de la cavité utérine."),
        ("Cancer du sein", "Tumeur maligne des tissus mammaires, la plus fréquente chez la femme."),
        ("Cancer du col de l’utérus", "Tumeur maligne du col utérin, principalement due à l’infection par le papillomavirus humain."),
        ("Infertilité", "Incapacité à concevoir après un an de rapports non protégés."),
        ("Cancer de la prostate", "Tumeur maligne de la prostate, fréquente chez l’homme après 50 ans."),
        ("Dysfonction érectile", "Incapacité persistante à obtenir ou maintenir une érection suffisante pour un rapport sexuel."),
        ("Kyste ovarien", "Formation kystique sur un ovaire, le plus souvent bénigne."),
        ("Fibromes utérins", "Tumeurs bénignes du muscle utérin, également appelées myomes."),
        ("Vulvovaginite", "Inflammation de la vulve et du vagin, d’origine infectieuse ou irritative."),
        ("Cryptorchidie", "Absence de descente complète d’un ou des deux testicules dans le scrotum."),
    ],
}
}